# coding: utf-8

"""
    DmsApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'subject': 'str',
        'page_count': 'int',
        'size': 'int',
        'is_encrypted': 'bool',
        'pdf_compliance': 'str',
        'is_signed': 'bool',
        'uploaded_mime_type': 'str',
        'uploaded_file_size': 'int'
    }

    attribute_map = {
        'title': 'title',
        'subject': 'subject',
        'page_count': 'pageCount',
        'size': 'size',
        'is_encrypted': 'isEncrypted',
        'pdf_compliance': 'pdfCompliance',
        'is_signed': 'isSigned',
        'uploaded_mime_type': 'uploadedMimeType',
        'uploaded_file_size': 'uploadedFileSize'
    }

    def __init__(self, title=None, subject=None, page_count=None, size=None, is_encrypted=None, pdf_compliance=None, is_signed=None, uploaded_mime_type=None, uploaded_file_size=None):  # noqa: E501
        """DocMetadata - a model defined in Swagger"""  # noqa: E501

        self._title = None
        self._subject = None
        self._page_count = None
        self._size = None
        self._is_encrypted = None
        self._pdf_compliance = None
        self._is_signed = None
        self._uploaded_mime_type = None
        self._uploaded_file_size = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if subject is not None:
            self.subject = subject
        self.page_count = page_count
        self.size = size
        self.is_encrypted = is_encrypted
        if pdf_compliance is not None:
            self.pdf_compliance = pdf_compliance
        self.is_signed = is_signed
        if uploaded_mime_type is not None:
            self.uploaded_mime_type = uploaded_mime_type
        self.uploaded_file_size = uploaded_file_size

    @property
    def title(self):
        """Gets the title of this DocMetadata.  # noqa: E501


        :return: The title of this DocMetadata.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this DocMetadata.


        :param title: The title of this DocMetadata.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def subject(self):
        """Gets the subject of this DocMetadata.  # noqa: E501


        :return: The subject of this DocMetadata.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this DocMetadata.


        :param subject: The subject of this DocMetadata.  # noqa: E501
        :type: str
        """

        self._subject = subject

    @property
    def page_count(self):
        """Gets the page_count of this DocMetadata.  # noqa: E501


        :return: The page_count of this DocMetadata.  # noqa: E501
        :rtype: int
        """
        return self._page_count

    @page_count.setter
    def page_count(self, page_count):
        """Sets the page_count of this DocMetadata.


        :param page_count: The page_count of this DocMetadata.  # noqa: E501
        :type: int
        """
        if page_count is None:
            raise ValueError("Invalid value for `page_count`, must not be `None`")  # noqa: E501

        self._page_count = page_count

    @property
    def size(self):
        """Gets the size of this DocMetadata.  # noqa: E501


        :return: The size of this DocMetadata.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this DocMetadata.


        :param size: The size of this DocMetadata.  # noqa: E501
        :type: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def is_encrypted(self):
        """Gets the is_encrypted of this DocMetadata.  # noqa: E501


        :return: The is_encrypted of this DocMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_encrypted

    @is_encrypted.setter
    def is_encrypted(self, is_encrypted):
        """Sets the is_encrypted of this DocMetadata.


        :param is_encrypted: The is_encrypted of this DocMetadata.  # noqa: E501
        :type: bool
        """
        if is_encrypted is None:
            raise ValueError("Invalid value for `is_encrypted`, must not be `None`")  # noqa: E501

        self._is_encrypted = is_encrypted

    @property
    def pdf_compliance(self):
        """Gets the pdf_compliance of this DocMetadata.  # noqa: E501


        :return: The pdf_compliance of this DocMetadata.  # noqa: E501
        :rtype: str
        """
        return self._pdf_compliance

    @pdf_compliance.setter
    def pdf_compliance(self, pdf_compliance):
        """Sets the pdf_compliance of this DocMetadata.


        :param pdf_compliance: The pdf_compliance of this DocMetadata.  # noqa: E501
        :type: str
        """

        self._pdf_compliance = pdf_compliance

    @property
    def is_signed(self):
        """Gets the is_signed of this DocMetadata.  # noqa: E501


        :return: The is_signed of this DocMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_signed

    @is_signed.setter
    def is_signed(self, is_signed):
        """Sets the is_signed of this DocMetadata.


        :param is_signed: The is_signed of this DocMetadata.  # noqa: E501
        :type: bool
        """
        if is_signed is None:
            raise ValueError("Invalid value for `is_signed`, must not be `None`")  # noqa: E501

        self._is_signed = is_signed

    @property
    def uploaded_mime_type(self):
        """Gets the uploaded_mime_type of this DocMetadata.  # noqa: E501


        :return: The uploaded_mime_type of this DocMetadata.  # noqa: E501
        :rtype: str
        """
        return self._uploaded_mime_type

    @uploaded_mime_type.setter
    def uploaded_mime_type(self, uploaded_mime_type):
        """Sets the uploaded_mime_type of this DocMetadata.


        :param uploaded_mime_type: The uploaded_mime_type of this DocMetadata.  # noqa: E501
        :type: str
        """

        self._uploaded_mime_type = uploaded_mime_type

    @property
    def uploaded_file_size(self):
        """Gets the uploaded_file_size of this DocMetadata.  # noqa: E501


        :return: The uploaded_file_size of this DocMetadata.  # noqa: E501
        :rtype: int
        """
        return self._uploaded_file_size

    @uploaded_file_size.setter
    def uploaded_file_size(self, uploaded_file_size):
        """Sets the uploaded_file_size of this DocMetadata.


        :param uploaded_file_size: The uploaded_file_size of this DocMetadata.  # noqa: E501
        :type: int
        """
        if uploaded_file_size is None:
            raise ValueError("Invalid value for `uploaded_file_size`, must not be `None`")  # noqa: E501

        self._uploaded_file_size = uploaded_file_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
