# coding: utf-8

"""
    DmsApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pdf4me.model.document import Document  # noqa: F401,E501
from pdf4me.model.extract_action import ExtractAction  # noqa: F401,E501
from pdf4me.model.notification import Notification  # noqa: F401,E501


class Extract(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document': 'Document',
        'extract_action': 'ExtractAction',
        'notification': 'Notification'
    }

    attribute_map = {
        'document': 'document',
        'extract_action': 'extractAction',
        'notification': 'notification'
    }

    def __init__(self, document=None, extract_action=None, notification=None):  # noqa: E501
        """Extract - a model defined in Swagger"""  # noqa: E501

        self._document = None
        self._extract_action = None
        self._notification = None
        self.discriminator = None

        if document is not None:
            self.document = document
        if extract_action is not None:
            self.extract_action = extract_action
        if notification is not None:
            self.notification = notification

    @property
    def document(self):
        """Gets the document of this Extract.  # noqa: E501


        :return: The document of this Extract.  # noqa: E501
        :rtype: Document
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this Extract.


        :param document: The document of this Extract.  # noqa: E501
        :type: Document
        """

        self._document = document

    @property
    def extract_action(self):
        """Gets the extract_action of this Extract.  # noqa: E501


        :return: The extract_action of this Extract.  # noqa: E501
        :rtype: ExtractAction
        """
        return self._extract_action

    @extract_action.setter
    def extract_action(self, extract_action):
        """Sets the extract_action of this Extract.


        :param extract_action: The extract_action of this Extract.  # noqa: E501
        :type: ExtractAction
        """

        self._extract_action = extract_action

    @property
    def notification(self):
        """Gets the notification of this Extract.  # noqa: E501

        Set Notification  # noqa: E501

        :return: The notification of this Extract.  # noqa: E501
        :rtype: Notification
        """
        return self._notification

    @notification.setter
    def notification(self, notification):
        """Sets the notification of this Extract.

        Set Notification  # noqa: E501

        :param notification: The notification of this Extract.  # noqa: E501
        :type: Notification
        """

        self._notification = notification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Extract):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
