# coding: utf-8

"""
    Pdf4me

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pdf4me.model.doc_log import DocLog  # noqa: F401,E501
from pdf4me.model.doc_metadata import DocMetadata  # noqa: F401,E501
from pdf4me.model.pdf4me_document import Pdf4meDocument  # noqa: F401,E501
from pdf4me.model.pricing import Pricing  # noqa: F401,E501


class GetDocumentListRes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_id': 'str',
        'doc_logs': 'list[DocLog]',
        'pricing': 'Pricing',
        'document_list': 'list[Pdf4meDocument]',
        'document': 'Pdf4meDocument',
        'in_doc_metadata': 'DocMetadata',
        'in_doc_metadata_list': 'list[DocMetadata]'
    }

    attribute_map = {
        'job_id': 'jobId',
        'doc_logs': 'docLogs',
        'pricing': 'pricing',
        'document_list': 'documentList',
        'document': 'document',
        'in_doc_metadata': 'inDocMetadata',
        'in_doc_metadata_list': 'inDocMetadataList'
    }

    def __init__(self, job_id=None, doc_logs=None, pricing=None, document_list=None, document=None, in_doc_metadata=None, in_doc_metadata_list=None):  # noqa: E501
        """GetDocumentListRes - a model defined in Swagger"""  # noqa: E501

        self._job_id = None
        self._doc_logs = None
        self._pricing = None
        self._document_list = None
        self._document = None
        self._in_doc_metadata = None
        self._in_doc_metadata_list = None
        self.discriminator = None

        if job_id is not None:
            self.job_id = job_id
        if doc_logs is not None:
            self.doc_logs = doc_logs
        if pricing is not None:
            self.pricing = pricing
        if document_list is not None:
            self.document_list = document_list
        if document is not None:
            self.document = document
        if in_doc_metadata is not None:
            self.in_doc_metadata = in_doc_metadata
        if in_doc_metadata_list is not None:
            self.in_doc_metadata_list = in_doc_metadata_list

    @property
    def job_id(self):
        """Gets the job_id of this GetDocumentListRes.  # noqa: E501


        :return: The job_id of this GetDocumentListRes.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this GetDocumentListRes.


        :param job_id: The job_id of this GetDocumentListRes.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def doc_logs(self):
        """Gets the doc_logs of this GetDocumentListRes.  # noqa: E501


        :return: The doc_logs of this GetDocumentListRes.  # noqa: E501
        :rtype: list[DocLog]
        """
        return self._doc_logs

    @doc_logs.setter
    def doc_logs(self, doc_logs):
        """Sets the doc_logs of this GetDocumentListRes.


        :param doc_logs: The doc_logs of this GetDocumentListRes.  # noqa: E501
        :type: list[DocLog]
        """

        self._doc_logs = doc_logs

    @property
    def pricing(self):
        """Gets the pricing of this GetDocumentListRes.  # noqa: E501


        :return: The pricing of this GetDocumentListRes.  # noqa: E501
        :rtype: Pricing
        """
        return self._pricing

    @pricing.setter
    def pricing(self, pricing):
        """Sets the pricing of this GetDocumentListRes.


        :param pricing: The pricing of this GetDocumentListRes.  # noqa: E501
        :type: Pricing
        """

        self._pricing = pricing

    @property
    def document_list(self):
        """Gets the document_list of this GetDocumentListRes.  # noqa: E501


        :return: The document_list of this GetDocumentListRes.  # noqa: E501
        :rtype: list[Pdf4meDocument]
        """
        return self._document_list

    @document_list.setter
    def document_list(self, document_list):
        """Sets the document_list of this GetDocumentListRes.


        :param document_list: The document_list of this GetDocumentListRes.  # noqa: E501
        :type: list[Pdf4meDocument]
        """

        self._document_list = document_list

    @property
    def document(self):
        """Gets the document of this GetDocumentListRes.  # noqa: E501


        :return: The document of this GetDocumentListRes.  # noqa: E501
        :rtype: Pdf4meDocument
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this GetDocumentListRes.


        :param document: The document of this GetDocumentListRes.  # noqa: E501
        :type: Pdf4meDocument
        """

        self._document = document

    @property
    def in_doc_metadata(self):
        """Gets the in_doc_metadata of this GetDocumentListRes.  # noqa: E501


        :return: The in_doc_metadata of this GetDocumentListRes.  # noqa: E501
        :rtype: DocMetadata
        """
        return self._in_doc_metadata

    @in_doc_metadata.setter
    def in_doc_metadata(self, in_doc_metadata):
        """Sets the in_doc_metadata of this GetDocumentListRes.


        :param in_doc_metadata: The in_doc_metadata of this GetDocumentListRes.  # noqa: E501
        :type: DocMetadata
        """

        self._in_doc_metadata = in_doc_metadata

    @property
    def in_doc_metadata_list(self):
        """Gets the in_doc_metadata_list of this GetDocumentListRes.  # noqa: E501


        :return: The in_doc_metadata_list of this GetDocumentListRes.  # noqa: E501
        :rtype: list[DocMetadata]
        """
        return self._in_doc_metadata_list

    @in_doc_metadata_list.setter
    def in_doc_metadata_list(self, in_doc_metadata_list):
        """Sets the in_doc_metadata_list of this GetDocumentListRes.


        :param in_doc_metadata_list: The in_doc_metadata_list of this GetDocumentListRes.  # noqa: E501
        :type: list[DocMetadata]
        """

        self._in_doc_metadata_list = in_doc_metadata_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetDocumentListRes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetDocumentListRes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
