# coding: utf-8

"""
    Pdf4me

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RunJobFlow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'documents': 'list[Document]',
        'job_flow_id': 'str',
        'job_flow_name': 'str',
        'action_flow': 'ActionFlow',
        'job_flow_action': 'JobFlowAction',
        'ip_address': 'str',
        'job_id': 'str',
        'job_id_ext': 'str',
        'integrations': 'list[str]'
    }

    attribute_map = {
        'documents': 'documents',
        'job_flow_id': 'jobFlowId',
        'job_flow_name': 'jobFlowName',
        'action_flow': 'actionFlow',
        'job_flow_action': 'jobFlowAction',
        'ip_address': 'ipAddress',
        'job_id': 'jobId',
        'job_id_ext': 'jobIdExt',
        'integrations': 'integrations'
    }

    def __init__(self, documents=None, job_flow_id=None, job_flow_name=None, action_flow=None, job_flow_action=None, ip_address=None, job_id=None, job_id_ext=None, integrations=None):  # noqa: E501
        """RunJobFlow - a model defined in Swagger"""  # noqa: E501

        self._documents = None
        self._job_flow_id = None
        self._job_flow_name = None
        self._action_flow = None
        self._job_flow_action = None
        self._ip_address = None
        self._job_id = None
        self._job_id_ext = None
        self._integrations = None
        self.discriminator = None

        if documents is not None:
            self.documents = documents
        if job_flow_id is not None:
            self.job_flow_id = job_flow_id
        if job_flow_name is not None:
            self.job_flow_name = job_flow_name
        if action_flow is not None:
            self.action_flow = action_flow
        if job_flow_action is not None:
            self.job_flow_action = job_flow_action
        if ip_address is not None:
            self.ip_address = ip_address
        if job_id is not None:
            self.job_id = job_id
        if job_id_ext is not None:
            self.job_id_ext = job_id_ext
        if integrations is not None:
            self.integrations = integrations

    @property
    def documents(self):
        """Gets the documents of this RunJobFlow.  # noqa: E501


        :return: The documents of this RunJobFlow.  # noqa: E501
        :rtype: list[Document]
        """
        return self._documents

    @documents.setter
    def documents(self, documents):
        """Sets the documents of this RunJobFlow.


        :param documents: The documents of this RunJobFlow.  # noqa: E501
        :type: list[Document]
        """

        self._documents = documents

    @property
    def job_flow_id(self):
        """Gets the job_flow_id of this RunJobFlow.  # noqa: E501


        :return: The job_flow_id of this RunJobFlow.  # noqa: E501
        :rtype: str
        """
        return self._job_flow_id

    @job_flow_id.setter
    def job_flow_id(self, job_flow_id):
        """Sets the job_flow_id of this RunJobFlow.


        :param job_flow_id: The job_flow_id of this RunJobFlow.  # noqa: E501
        :type: str
        """

        self._job_flow_id = job_flow_id

    @property
    def job_flow_name(self):
        """Gets the job_flow_name of this RunJobFlow.  # noqa: E501


        :return: The job_flow_name of this RunJobFlow.  # noqa: E501
        :rtype: str
        """
        return self._job_flow_name

    @job_flow_name.setter
    def job_flow_name(self, job_flow_name):
        """Sets the job_flow_name of this RunJobFlow.


        :param job_flow_name: The job_flow_name of this RunJobFlow.  # noqa: E501
        :type: str
        """

        self._job_flow_name = job_flow_name

    @property
    def action_flow(self):
        """Gets the action_flow of this RunJobFlow.  # noqa: E501


        :return: The action_flow of this RunJobFlow.  # noqa: E501
        :rtype: ActionFlow
        """
        return self._action_flow

    @action_flow.setter
    def action_flow(self, action_flow):
        """Sets the action_flow of this RunJobFlow.


        :param action_flow: The action_flow of this RunJobFlow.  # noqa: E501
        :type: ActionFlow
        """

        self._action_flow = action_flow

    @property
    def job_flow_action(self):
        """Gets the job_flow_action of this RunJobFlow.  # noqa: E501


        :return: The job_flow_action of this RunJobFlow.  # noqa: E501
        :rtype: JobFlowAction
        """
        return self._job_flow_action

    @job_flow_action.setter
    def job_flow_action(self, job_flow_action):
        """Sets the job_flow_action of this RunJobFlow.


        :param job_flow_action: The job_flow_action of this RunJobFlow.  # noqa: E501
        :type: JobFlowAction
        """

        self._job_flow_action = job_flow_action

    @property
    def ip_address(self):
        """Gets the ip_address of this RunJobFlow.  # noqa: E501


        :return: The ip_address of this RunJobFlow.  # noqa: E501
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address):
        """Sets the ip_address of this RunJobFlow.


        :param ip_address: The ip_address of this RunJobFlow.  # noqa: E501
        :type: str
        """

        self._ip_address = ip_address

    @property
    def job_id(self):
        """Gets the job_id of this RunJobFlow.  # noqa: E501


        :return: The job_id of this RunJobFlow.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this RunJobFlow.


        :param job_id: The job_id of this RunJobFlow.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def job_id_ext(self):
        """Gets the job_id_ext of this RunJobFlow.  # noqa: E501


        :return: The job_id_ext of this RunJobFlow.  # noqa: E501
        :rtype: str
        """
        return self._job_id_ext

    @job_id_ext.setter
    def job_id_ext(self, job_id_ext):
        """Sets the job_id_ext of this RunJobFlow.


        :param job_id_ext: The job_id_ext of this RunJobFlow.  # noqa: E501
        :type: str
        """

        self._job_id_ext = job_id_ext

    @property
    def integrations(self):
        """Gets the integrations of this RunJobFlow.  # noqa: E501


        :return: The integrations of this RunJobFlow.  # noqa: E501
        :rtype: list[str]
        """
        return self._integrations

    @integrations.setter
    def integrations(self, integrations):
        """Sets the integrations of this RunJobFlow.


        :param integrations: The integrations of this RunJobFlow.  # noqa: E501
        :type: list[str]
        """

        self._integrations = integrations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunJobFlow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunJobFlow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
