# coding: utf-8

"""
    Pdf4me

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SignAction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'signing_provider': 'SigningProvider',
        'name': 'str',
        'action_id': 'str'
    }

    attribute_map = {
        'signing_provider': 'signingProvider',
        'name': 'name',
        'action_id': 'actionId'
    }

    def __init__(self, signing_provider=None, name=None, action_id=None):  # noqa: E501
        """SignAction - a model defined in Swagger"""  # noqa: E501

        self._signing_provider = None
        self._name = None
        self._action_id = None
        self.discriminator = None

        if signing_provider is not None:
            self.signing_provider = signing_provider
        if name is not None:
            self.name = name
        if action_id is not None:
            self.action_id = action_id

    @property
    def signing_provider(self):
        """Gets the signing_provider of this SignAction.  # noqa: E501


        :return: The signing_provider of this SignAction.  # noqa: E501
        :rtype: SigningProvider
        """
        return self._signing_provider

    @signing_provider.setter
    def signing_provider(self, signing_provider):
        """Sets the signing_provider of this SignAction.


        :param signing_provider: The signing_provider of this SignAction.  # noqa: E501
        :type: SigningProvider
        """

        self._signing_provider = signing_provider

    @property
    def name(self):
        """Gets the name of this SignAction.  # noqa: E501


        :return: The name of this SignAction.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SignAction.


        :param name: The name of this SignAction.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def action_id(self):
        """Gets the action_id of this SignAction.  # noqa: E501


        :return: The action_id of this SignAction.  # noqa: E501
        :rtype: str
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id):
        """Sets the action_id of this SignAction.


        :param action_id: The action_id of this SignAction.  # noqa: E501
        :type: str
        """

        self._action_id = action_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SignAction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
